"""OpenAI-compatible chat completion models.

These models follow the OpenAI API specification to ensure
compatibility with existing clients and tools.
"""

from typing import Literal

from pydantic import BaseModel, Field


class ChatMessage(BaseModel):
    """A single message in a chat conversation.

    Attributes:
        role: The role of the message author (system, user, assistant).
        content: The content of the message.
    """

    role: Literal["system", "user", "assistant"] = "user"
    content: str = ""


class DeltaMessage(BaseModel):
    """A delta message for streaming responses.

    Attributes:
        role: The role of the message author, if present in this chunk.
        content: The content delta, if present in this chunk.
    """

    role: Literal["assistant"] | None = None
    content: str | None = None


class Choice(BaseModel):
    """A single completion choice.

    Attributes:
        index: The index of this choice in the list.
        message: The message generated by the model.
        finish_reason: The reason the completion finished.
    """

    index: int = 0
    message: ChatMessage
    finish_reason: Literal["stop", "length", "content_filter"] | None = "stop"


class StreamChoice(BaseModel):
    """A single streaming completion choice.

    Attributes:
        index: The index of this choice in the list.
        delta: The delta message for this chunk.
        finish_reason: The reason the completion finished, if done.
    """

    index: int = 0
    delta: DeltaMessage
    finish_reason: Literal["stop", "length", "content_filter"] | None = None


class Usage(BaseModel):
    """Token usage statistics for a completion request.

    Attributes:
        prompt_tokens: Number of tokens in the prompt.
        completion_tokens: Number of tokens in the completion.
        total_tokens: Total number of tokens used.
    """

    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0


class ChatCompletionRequest(BaseModel):
    """Request body for chat completion endpoint.

    Attributes:
        model: The model to use for completion.
        messages: List of messages in the conversation.
        temperature: Sampling temperature (0.0 to 2.0).
        max_tokens: Maximum tokens to generate.
        stream: Whether to stream the response.
        top_p: Nucleus sampling parameter.
    """

    model: str = "muse-spark"
    messages: list[ChatMessage]
    temperature: float = Field(default=0.7, ge=0.0, le=2.0)
    max_tokens: int | None = Field(default=None, ge=1)
    stream: bool = False
    top_p: float = Field(default=1.0, ge=0.0, le=1.0)


class ChatCompletionResponse(BaseModel):
    """Standard (non-streaming) chat completion response.

    Attributes:
        id: Unique identifier for this completion.
        object: Object type, always 'chat.completion'.
        created: Unix timestamp of creation.
        model: The model used for completion.
        choices: List of completion choices.
        usage: Token usage statistics.
    """

    id: str
    object: Literal["chat.completion"] = "chat.completion"
    created: int
    model: str
    choices: list[Choice]
    usage: Usage


class ChatCompletionStreamResponse(BaseModel):
    """Streaming chat completion response chunk.

    Attributes:
        id: Unique identifier for this completion.
        object: Object type, always 'chat.completion.chunk'.
        created: Unix timestamp of creation.
        model: The model used for completion.
        choices: List of streaming choices.
    """

    id: str
    object: Literal["chat.completion.chunk"] = "chat.completion.chunk"
    created: int
    model: str
    choices: list[StreamChoice]
